default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  

development:
  <<: *default
  username: postgres
  password: db1234
  host: localhost
  port: 5434
  database: hello_world_3010_development

test:
  <<: *default
  username: postgres
  password: db1234
  host: localhost
  port: 5434
  database: hello_world_3010_test

production:
  <<: *default
  database: d1oolq9meariev
  username: rzewwgydhtuxwi
  password: 0d8b47d26ff58ec881fb664d9c63169943b1e6f86ce60b9f926da148a14d4151
  host: ec2-3-222-150-253.compute-1.amazonaws.com
  port: 5432
